#+SETUPFILE: setup.org

* Contents                                                         :toc_3_gh:
 - [[#the-blackboard-model][The blackboard model]]
   - [[#the-metaphor][The metaphor]]
     - [[#formalised-metaphor-citecraig1988][Formalised metaphor cite:Craig1988]]
   - [[#expertsknowledge-sources][Experts/knowledge sources]]
   - [[#triggering-condition][Triggering condition]]
   - [[#independence-of-expertise][Independence of expertise]]
   - [[#diversity-in-problem-solving-techniques][Diversity in problem-solving techniques]]
   - [[#flexible-representation-of-blackboard-information][Flexible representation of blackboard information]]
   - [[#how-does-it-differ-to-rule-based-systems][How does it differ to rule based systems?]]
   - [[#problems][Problems]]
   - [[#why][Why?]]

* The blackboard model

"Unlike most AI problem-solving techniques that implement formal models, 
the blackboard approach was designed as a means for dealing with ill-defined, complex applications."
cite:Craig1988

Misztal stated that the blackboard model "has a potential to be used in simulating cognitive processes such as creativity." 
cite:Misztal2014 

** The metaphor 

"Imagine a group of human specialists seated next to a large blackboard. 
The specialists are working cooperatively to solve a problem, 
using the blackboard as the workplace for developing the solution.

Problem solving begins when the problem and initial data are written onto the blackboard.
The specialists watch the blackboard, looking for an opportunity to apply their expertise to the developing solution.
When a specialist finds sufficient information to make a contribution,
she records the contribution on the blackboard,
hopefully enabling other specialists to apply their expertise.
This process of adding contributions to the blackboard continues until the problem has been solved."
cite:Craig1988

*** Formalised metaphor cite:Craig1988 

- Knowledge sources (KSs) are independent modules that contain the knowledge needed to solve the problem. KSs can be widely diverse in representation and inference techniques.
- The blackboard is a global database containing input data, partial solutions, and other data that are in various problem-solving states.
- A control component makes runtime decisions about the course of problem solving and the expenditure of problem-solving resources. The control component is separate from the individual KSs. In some blackboard systems, the control component itself is implemented using a blackboard approach (involving control KSs and blackboard areas devoted to control)

** Experts/knowledge sources

Experts were traditionally referred to as knowledge sources or KS.

This seems to have stopped and we now call them experts again (cite:Misztal2014)

each "can solve certain aspects of an overall problem"
"No KS requires other KSs in making its contribution"
"Once it finds the information it needs on the blackboard,
 it can proceed without any assistance from other KSs."

"without changing any other KSs, 
additional KSs can be added to the blackboard system,
poorer performing KSs can be enhanced, 
and inappropriate KSs can be removed."

"the internal representation and inferencing machinery used by each KS is similarly hidden from direct view."
"each KS as a black box"

"A KS needs no knowledge of the expertise, or even the existence, of the others;
however, it must be able to understand the state of the problem-solving process and the representation of relevant information on the blackboard."

** Triggering condition
"Each KS knows the conditions under which it can contribute to the solution"

cite:Craig1988

** Independence of expertise

Experts are "not trained to work solely with that specific group of specialists" 
and may have 
"learned their expertise in vastly different situations."
"a specialist is a self-contained expert on some aspects of the problem and can contribute to the solution independently of the particular mix of other specialists in the room."
In blackboard systems "have this functional modularization of expertise".
cite:Craig1988

** Diversity in problem-solving techniques

"It does not matter if one KS is a forward-chaining rule-based system,
another uses a neural network approach, another uses a linear-programming algorithm,
and still another is a procedural simulation program."
cite:Craig1988

** Flexible representation of blackboard information

"could use any intelligible doodles when adding their contributions to the blackboard.
They might use formulas, diagrams, sentences, checklists, and numerous circles and arrows."

"The blackboard model does not place any prior restrictions on what information can be placed on the blackboard."

"One blackboard application might use assertional blackboard data and require that consistency be maintained.
Another application might allow incompatible alternatives to be maintained on the blackboard,
with each alternative available for opportunistic exploration of the solution."

cite:Craig1988

** How does it differ to rule based systems?

"Rule-based systems are also modular, but at the level of individual rules.
Unlike the large-grained scope of KSs, 
the small size of each rule prevents full independence.
A pair of rules that implement iteration by using a counter value and a termination rule is an example of two rules that cannot be designed independently or removed individually without affecting the performance of the other rule."
cite:Craig1988

** Problems

"the lack of formal specifications has also contributed to confusion about blackboard systems and their proper place in the AI problem-solving toolkit."
cite:Craig1988

** Why?

"systems which combine various forms of reasoning have repeatedly shown to be more effective than stand-alone systems"

Charnley showed with GC toolkit that "the framework can combine machine learning, example construction and theorem proving processes to perform automated theory formation"

cite:charnley2008

"Opportunistic is a buzzword intimately associated with blackboard systems.
It means having the control flexibility to perform the most appropriate problem-solving action at each step in the solution process."

"blackboards are particularly effective when there are many steps towards the solution and many potential paths involving those steps."

cite:Craig1988
